version: "2"

linters:
  default: standard
  exclusions:
    rules:
      # Ignore unchecked errors on Close/Remove in deferred cleanup calls
      - linters: [errcheck]
        source: "defer "
      - linters: [errcheck]
        source: "\\.Close\\(\\)"
      - linters: [errcheck]
        source: "os\\.Remove\\("
      # Ignore unchecked errors in test files
      - linters: [errcheck]
        path: "_test\\.go"
